### ISSUE TITLE
Уебанская хуета и руководство говно!!!

### ISSUE THREAD

**Issue by dmt-space** [PedroBern/django-graphql-auth#141]
quirement already satisfied: sqlparse>=0.2.2 in ./.venv/lib/python3.8/site-packages (from Django>=2.1.0->django-graphql-auth) (0.4.2)
Requirement already satisfied: rx<2,>=1.6 in ./.venv/lib/python3.8/site-packages (from graphql-core<3,>=2.1->django-graphql-jwt==0.3.0->django-graphql-auth) (1.6.1)
ERROR: graphql-relay 3.1.4 has requirement graphql-core<3.2,>=3.1, but you'll have graphql-core 2.3.2 which is incompatible.
ERROR: graphene 3.0 has requirement graphql-core~=3.1.2, but you'll have graphql-core 2.3.2 which is incompatible.
ERROR: graphene-django 2.15.0 has requirement graphene<3,>=2.1.7, but you'll have graphene 3.0 which is incompatible.
Installing collected packages: graphql-core
  Attempting uninstall: graphql-core
    Found existing installation: graphql-core 3.1.7
    Uninstalling graphql-core-3.1.7:
      Successfully uninstalled graphql-core-3.1.7
Successfully installed graphql-core-2.3.2
(.venv) dmt@inject:~/develop/SIM-TAC$ python3 manage.py makemigrations
Migrations for 'graphql_auth':
  .venv/lib/python3.8/site-packages/graphql_auth/migrations/0002_alter_userstatus_id.py
    - Alter field id on userstatus
(.venv) dmt@inject:~/develop/SIM-TAC$ python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, graphql_auth, sessions, users
Running migrations:
  Applying graphql_auth.0001_initial... OK
  Applying graphql_auth.0002_alter_userstatus_id... OK
(.venv) dmt@inject:~/develop/SIM-TAC$ pip install pyyaml
Collecting pyyaml
  Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
     |████████████████████████████████| 701 kB 14.2 MB/s
Installing collected packages: pyyaml
Successfully installed pyyaml-6.0
(.venv) dmt@inject:~/develop/SIM-TAC$ pip install django-graphql-jwt
Requirement already satisfied: django-graphql-jwt in ./.venv/lib/python3.8/site-packages (0.3.0)
Requirement already satisfied: graphene-django>=2.0.0 in ./.venv/lib/python3.8/site-packages (from django-graphql-jwt) (2.15.0)
Requirement already satisfied: PyJWT>=1.5.0 in ./.venv/lib/python3.8/site-packages (from django-graphql-jwt) (1.7.1)
Requirement already satisfied: Django>=1.11 in ./.venv/lib/python3.8/site-packages (from django-graphql-jwt) (4.0.1)
Requirement already satisfied: graphql-core<3,>=2.1 in ./.venv/lib/python3.8/site-packages (from django-graphql-jwt) (2.3.2)
Requirement already satisfied: six>=1.10.0 in ./.venv/lib/python3.8/site-packages (from graphene-django>=2.0.0->django-graphql-jwt) (1.16.0)
Requirement already satisfied: text-unidecode in ./.venv/lib/python3.8/site-packages (from graphene-django>=2.0.0->django-graphql-jwt) (1.3)
Requirement already satisfied: promise>=2.1 in ./.venv/lib/python3.8/site-packages (from graphene-django>=2.0.0->django-graphql-jwt) (2.3)
Collecting graphene<3,>=2.1.7
  Downloading graphene-2.1.9-py2.py3-none-any.whl (107 kB)
     |████████████████████████████████| 107 kB 14.2 MB/s
Requirement already satisfied: singledispatch>=3.4.0.3 in ./.venv/lib/python3.8/site-packages (from graphene-django>=2.0.0->django-graphql-jwt) (3.7.0)
Requirement already satisfied: sqlparse>=0.2.2 in ./.venv/lib/python3.8/site-packages (from Django>=1.11->django-graphql-jwt) (0.4.2)
Requirement already satisfied: asgiref<4,>=3.4.1 in ./.venv/lib/python3.8/site-packages (from Django>=1.11->django-graphql-jwt) (3.4.1)
Requirement already satisfied: backports.zoneinfo; python_version < "3.9" in ./.venv/lib/python3.8/site-packages (from Django>=1.11->django-graphql-jwt) (0.2.1)
Requirement already satisfied: rx<2,>=1.6 in ./.venv/lib/python3.8/site-packages (from graphql-core<3,>=2.1->django-graphql-jwt) (1.6.1)
Collecting graphql-relay<3,>=2
  Downloading graphql_relay-2.0.1-py3-none-any.whl (20 kB)
Collecting aniso8601<=7,>=3
  Downloading aniso8601-7.0.0-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.6 MB/s
Installing collected packages: graphql-relay, aniso8601, graphene
  Attempting uninstall: graphql-relay
    Found existing installation: graphql-relay 3.1.4
    Uninstalling graphql-relay-3.1.4:
      Successfully uninstalled graphql-relay-3.1.4
  Attempting uninstall: aniso8601
    Found existing installation: aniso8601 9.0.1
    Uninstalling aniso8601-9.0.1:
      Successfully uninstalled aniso8601-9.0.1
  Attempting uninstall: graphene
    Found existing installation: graphene 3.0
    Uninstalling graphene-3.0:
      Successfully uninstalled graphene-3.0
Successfully installed aniso8601-7.0.0 graphene-2.1.9 graphql-relay-2.0.1
(.venv) dmt@inject:~/develop/SIM-TAC$ pip install "graphene-django>=3"
ERROR: Could not find a version that satisfies the requirement graphene-django>=3 (from versions: 1.0.dev20160909000001, 1.0.dev20160910000001, 1.0.dev20160917000001, 1.0.dev20160919000001, 1.0.dev20160919000002, 1.0.dev20160919000003, 1.0.dev20160919000004, 1.0.dev20160920000001, 1.0.dev20160922000001, 1.0, 1.1.0, 1.2.0, 1.2.1, 1.3, 2.0.dev2017072501, 2.0.dev2017072601, 2.0.dev2017073101, 2.0.dev2017083101, 2.0.0, 2.1rc0, 2.1rc1, 2.1.0, 2.2.0, 2.3.0, 2.3.2, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.7.1, 2.8.0, 2.8.1, 2.8.2, 2.9.0, 2.9.1, 2.10.0, 2.10.1, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.13.0, 2.14.0, 2.15.0, 3.0.0b1, 3.0.0b2, 3.0.0b3, 3.0.0b4, 3.0.0b5, 3.0.0b6, 3.0.0b7)
ERROR: No matching distribution found for graphene-django>=3
(.venv) dmt@inject:~/develop/SIM-TAC$ pip install django-filter
Requirement already satisfied: django-filter in ./.venv/lib/python3.8/site-packages (21.1)
Requirement already satisfied: Django>=2.2 in ./.venv/lib/python3.8/site-packages (from django-filter) (4.0.1)
Requirement already satisfied: sqlparse>=0.2.2 in ./.venv/lib/python3.8/site-packages (from Django>=2.2->django-filter) (0.4.2)
Requirement already satisfied: backports.zoneinfo; python_version < "3.9" in ./.venv/lib/python3.8/site-packages (from Django>=2.2->django-filter) (0.2.1)
Requirement already satisfied: asgiref<4,>=3.4.1 in ./.venv/lib/python3.8/site-packages (from Django>=2.2->django-filter) (3.4.1)
(.venv) dmt@inject:~/develop/SIM-TAC$ python3 manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute
    django.setup()
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: staticfiles
(.venv) dmt@inject:~/develop/SIM-TAC$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute
    django.setup()
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: staticfiles
(.venv) dmt@inject:~/develop/SIM-TAC$ python3 manage.py runserver localhost:8001
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 115, in inner_run
    autoreload.raise_last_exception()
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute
    autoreload.check_errors(django.setup)()
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: staticfiles

^C(.venv) dmt@inject:~/develop/SIM-TAC$ython3 manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute
    django.setup()
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dmt/develop/SIM-TAC/.venv/lib/python3.8/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: staticfiles
(.venv) dmt@inject:~/develop/SIM-TAC$

**Comment by tamkovich** [comment]
🤡
