### ISSUE TITLE
Unknown field(s) (username) specified for User

### ISSUE THREAD

**Issue by udemezue01** [PedroBern/django-graphql-auth#54]
I get this error when I implement this into my existing custom user model that does not have a  username field attached to it.
my custom user model only supports email, full name and password.

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/

Django Version: 2.2.9
Python Version: 3.8.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'accounts',
 'post',
 'comment',
 'userprofile',
 'job',
 'schedule',
 'hashtag',
 'billing',
 'corsheaders',
 'graphene_django',
 'django_fsm_log',
 'subscriptions.apps.SubscriptionsConfig',
 'graphql_auth']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\core\handlers\exception.py" in inner
  34.             response = get_response(request)

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\core\handlers\base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\core\handlers\base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\views\decorators\csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\views\generic\base.py" in view
  62.             self = cls(**initkwargs)

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphene_django\views.py" in __init__
  79.             schema = graphene_settings.SCHEMA

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphene_django\settings.py" in __getattr__
  117.             val = perform_import(val, attr)

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphene_django\settings.py" in perform_import
  56.         return import_from_string(val, setting_name)

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphene_django\settings.py" in import_from_string
  70.         module = importlib.import_module(module_path)

File "C:\Users\Udemezue\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py" in import_module
  127.     return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>" in _gcd_import
  1014. <source code not available>

File "<frozen importlib._bootstrap>" in _find_and_load
  991. <source code not available>

File "<frozen importlib._bootstrap>" in _find_and_load_unlocked
  975. <source code not available>

File "<frozen importlib._bootstrap>" in _load_unlocked
  671. <source code not available>

File "<frozen importlib._bootstrap_external>" in exec_module
  783. <source code not available>

File "<frozen importlib._bootstrap>" in _call_with_frames_removed
  219. <source code not available>

File "C:\Users\Udemezue\Desktop\resume-backend\src\resume\resume\graph\schema.py" in <module>
  45. from graphql_auth import mutations

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphql_auth\mutations.py" in <module>
  5. from .mixins import (

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphql_auth\mixins.py" in <module>
  15. from .forms import RegisterForm, EmailForm, UpdateAccountForm

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphql_auth\forms.py" in <module>
  9. class RegisterForm(UserCreationForm):

File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\forms\models.py" in __new__
  266.                 raise FieldError(message)

Exception Type: FieldError at /
Exception Value: Unknown field(s) (username) specified for User

**Comment by PedroBern** [comment]
see if #9 helps

**Comment by udemezue01** [comment]
I don't understand sir, how do I fix it

**Comment by udemezue01** [comment]
The error about the username went way but I have the same errors with but the issue with the first name and the last name came up again


Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/

Django Version: 3.0.7
Python Version: 3.8.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'accounts',
 'post',
 'comment',
 'userprofile',
 'job',
 'schedule',
 'hashtag',
 'billing',
 'corsheaders',
 'graphene_django',
 'graphql_auth']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\views\generic\base.py", line 62, in view
    self = cls(**initkwargs)
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphene_django\views.py", line 79, in __init__
    schema = graphene_settings.SCHEMA
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphene_django\settings.py", line 117, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphene_django\settings.py", line 56, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphene_django\settings.py", line 70, in import_from_string
    module = importlib.import_module(module_path)
  File "C:\Users\Udemezue\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    <source code not available>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    <source code not available>
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    <source code not available>
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    <source code not available>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    <source code not available>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    <source code not available>
  File "C:\Users\Udemezue\Desktop\resume-backend\src\resume\resume\graph\schema.py", line 45, in <module>
    from graphql_auth import mutations
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphql_auth\mutations.py", line 5, in <module>
    from .mixins import (
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphql_auth\mixins.py", line 15, in <module>
    from .forms import RegisterForm, EmailForm, UpdateAccountForm
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\graphql_auth\forms.py", line 9, in <module>
    class RegisterForm(UserCreationForm):
  File "C:\Users\Udemezue\Desktop\resume-backend\env\lib\site-packages\django\forms\models.py", line 267, in __new__
    raise FieldError(message)

Exception Type: FieldError at /
Exception Value: Unknown field(s) (first_name, last_name) specified for User

**Comment by udemezue01** [comment]
I solved the issue already thanks

**Comment by mtusman** [comment]
How did you solve it? I'm dealing with the same issue.

**Comment by udemezue01** [comment]
i solved it by integrating with some environment variables, check the docs
