### ISSUE TITLE
User has no status error.

### ISSUE THREAD

**Issue by pors** [PedroBern/django-graphql-auth#7]
I follow the Quickstart guide and the query

```
query {
  users {
    edges {
      node {
        id,
        username,
        archived,
        verified,
        email,
        secondaryEmail,
      }
    }
  }
}
```

triggers the following error:

```
ERROR 2020-02-24 18:10:10,231 utils 26762 123145366966272 Traceback (most recent call last):
  File "/Users/mark/.pyenv/versions/ve381/lib/python3.8/site-packages/promise/promise.py", line 489, in _resolve_from_executor
    executor(resolve, reject)
  File "/Users/mark/.pyenv/versions/ve381/lib/python3.8/site-packages/promise/promise.py", line 756, in executor
    return resolve(f(*args, **kwargs))
  File "/Users/mark/.pyenv/versions/ve381/lib/python3.8/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/Users/mark/.pyenv/versions/ve381/lib/python3.8/site-packages/graphql_auth/schema.py", line 26, in resolve_archived
    return self.status.archived
  File "/Users/mark/.pyenv/versions/ve381/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 420, in __get__
    raise self.RelatedObjectDoesNotExist(
graphql.error.located_error.GraphQLLocatedError: User has no status.
```

The graphql result is:

```
{
  "errors": [
    {
      "message": "User has no status.",
      "locations": [
        {
          "line": 37,
          "column": 9
        }
      ],
      "path": [
        "users",
        "edges",
        0,
        "node",
        "archived"
      ]
    },
    {
      "message": "User has no status.",
      "locations": [
        {
          "line": 38,
          "column": 9
        }
      ],
      "path": [
        "users",
        "edges",
        0,
        "node",
        "verified"
      ]
    },
    {
      "message": "User has no status.",
      "locations": [
        {
          "line": 40,
          "column": 9
        }
      ],
      "path": [
        "users",
        "edges",
        0,
        "node",
        "secondaryEmail"
      ]
    },
    {
      "message": "User has no status.",
      "locations": [
        {
          "line": 37,
          "column": 9
        }
      ],
      "path": [
        "users",
        "edges",
        1,
        "node",
        "archived"
      ]
    },
    {
      "message": "User has no status.",
      "locations": [
        {
          "line": 38,
          "column": 9
        }
      ],
      "path": [
        "users",
        "edges",
        1,
        "node",
        "verified"
      ]
    },
    {
      "message": "User has no status.",
      "locations": [
        {
          "line": 40,
          "column": 9
        }
      ],
      "path": [
        "users",
        "edges",
        1,
        "node",
        "secondaryEmail"
      ]
    },
    {
      "message": "User has no status.",
      "locations": [
        {
          "line": 37,
          "column": 9
        }
      ],
      "path": [
        "users",
        "edges",
        2,
        "node",
        "archived"
      ]
    },
    {
      "message": "User has no status.",
      "locations": [
        {
          "line": 38,
          "column": 9
        }
      ],
      "path": [
        "users",
        "edges",
        2,
        "node",
        "verified"
      ]
    },
    {
      "message": "User has no status.",
      "locations": [
        {
          "line": 40,
          "column": 9
        }
      ],
      "path": [
        "users",
        "edges",
        2,
        "node",
        "secondaryEmail"
      ]
    }
  ],
  "data": {
    "users": {
      "edges": [
        {
          "node": {
            "id": "VXNlck5vZGU6MQ==",
            "username": "admin",
            "archived": null,
            "verified": null,
            "email": "***",
            "secondaryEmail": null
          }
        },
        {
          "node": {
            "id": "VXNlck5vZGU6Mg==",
            "username": "mark",
            "archived": null,
            "verified": null,
            "email": "***",
            "secondaryEmail": null
          }
        },
        {
          "node": {
            "id": "VXNlck5vZGU6Mw==",
            "username": "user1",
            "archived": null,
            "verified": null,
            "email": "user1@email.com",
            "secondaryEmail": null
          }
        },
        {
          "node": {
            "id": "VXNlck5vZGU6NA==",
            "username": "user2",
            "archived": false,
            "verified": true,
            "email": "user2@email.com",
            "secondaryEmail": null
          }
        },
        {
          "node": {
            "id": "VXNlck5vZGU6NQ==",
            "username": "user3",
            "archived": true,
            "verified": true,
            "email": "user3@email.com",
            "secondaryEmail": null
          }
        },
        {
          "node": {
            "id": "VXNlck5vZGU6Ng==",
            "username": "user4",
            "archived": false,
            "verified": true,
            "email": "user4@email.com",
            "secondaryEmail": "user4_secondary@email.com"
          }
        },
        {
          "node": {
            "id": "VXNlck5vZGU6Nw==",
            "username": "new",
            "archived": false,
            "verified": false,
            "email": "",
            "secondaryEmail": null
          }
        }
      ]
    }
  }
}
```

So both an error and a data response.
I already had two users and added the fixtures.

Note that I use a custom user table: `users_user`, which I have set in the settings as `AUTH_USER_MODEL = "users.User"`. I also changed that in the `users.json` file.

Could you please help me to debug this?

**Comment by PedroBern** [comment]
> I already had two users and added the fixtures.
 
The `UserStatus` is automatically created for each user when the user is created. Did these 2 users already exist before you install the `graphql_auth`?

Try manually creating the `UserStatus` for each user. In the same directory as `manage.py` run the following command to open the interactive shell:

```bash
./manage.py shell
```

Execute:
```python
from graphql_auth.models import UserStatus
from django.contrib.auth import get_user_model
UserModel = get_user_model()

for instance in UserModel._default_manager.all():
    UserStatus._default_manager.get_or_create(user=instance)
```

Then see if the query is working, and tell me.

**Comment by pors** [comment]
> The UserStatus is automatically created for each user when the user is created. Did these 2 users already exist before you install the graphql_auth?

Yes, they did, but doesn't the fixture also contain a user without a UserStatus? After loading users.json, user1 also doesn't have a UserStatus.

> Then see if the query is working, and tell me.

Yup, that solves it!

I wonder though if the error handling needs improvement there? Or is the mixed error/data output valid graphql?

**Comment by PedroBern** [comment]
> Yes, they did, but doesn't the fixture also contain a user without a UserStatus? After loading users.json, user1 also doesn't have a UserStatus.

You are right, but when you load the fixtures, the `graphql_auth` was already installed. This package will create a `UserStatus` instance on the `post_save` signal, you can see it [here](https://github.com/PedroBern/django-graphql-auth/blob/da09bf9fd73bbbe73eb42db84ec7cb7b1a2d443d/graphql_auth/signals.py#L9). So when you load the fixture, the signal automatically create the `UserStatus` instance.

> I wonder though if the error handling needs improvement there? Or is the mixed error/data output valid graphql?

It can be improved to not return data when there are errors, but meanwhile you can check if there are actual `errors` and handle it on the frontend. All `errors` inside the `data` are expected errors, e.g. form validations...

**Comment by pors** [comment]
Ah yes, you are right. Loading the fixture after graphql_auth was installed does create a UserStatus. Awesome!

Thanks for this lib, very useful!

**Comment by PedroBern** [comment]
> Thanks for this lib, very useful!

You are welcome!

**Comment by thongly** [comment]
@PedroBern - I came across this to. 

Would you accept a PR with a docs update explaining what to do if users already exist in the DB, and this as a utility function?

**Comment by PedroBern** [comment]
hi @thongly yes of course 👍
