### ISSUE TITLE
Login after register error: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by ariomoklo** [PedroBern/django-graphql-auth#89]
# Prerequisites

* [ ] Is it a bug?
* [ ] Is it a new feature?
* [x] Is it a question?
* [ ] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you check for similar issues?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/PedroBern/django-graphql-auth/blob/master/CONTRIBUTING.md) guide.

# Description

Hi, I am new to python and django. I followed the step explained in [Quickstart Documentation](https://django-graphql-auth.readthedocs.io/en/latest/quickstart/#register). But I encountered this error in registering the new user step:
``` json
{
  "errors": [
    {
      "message": "'str' object has no attribute 'decode'",
      "locations": [
        {
          "line": 33,
          "column": 3
        }
      ],
      "path": [
        "register"
      ]
    }
  ],
  "data": {
    "register": null
  }
}
```

terminal output:
```
Traceback (most recent call last):
  File "<path-to-project>\venv\lib\site-packages\promise\promise.py", line 489, in _resolve_from_executor
    executor(resolve, reject)
  File "<path-to-project>\venv\lib\site-packages\promise\promise.py", line 756, in executor
    return resolve(f(*args, **kwargs))
  File "<path-to-project>\venv\lib\site-packages\graphql\execution\middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "<path-to-project>\venv\lib\site-packages\graphql_auth\bases.py", line 31, in mutate
    return cls.resolve_mutation(root, info, **input)
  File "<path-to-project>\venv\lib\site-packages\graphql_auth\mixins.py", line 122, in resolve_mutation
    payload = cls.login_on_register(
  File "<path-to-project>\venv\lib\site-packages\graphql_jwt\decorators.py", line 110, in wrapper
    result = f(cls, root, info, **kwargs)
  File "<path-to-project>\venv\lib\site-packages\graphql_jwt\decorators.py", line 103, in wrapper
    return on_resolve(values)
  File "<path-to-project>\venv\lib\site-packages\graphql_jwt\decorators.py", line 74, in on_resolve
    payload.token = get_token(user, context)
  File "<path-to-project>\venv\lib\site-packages\graphql_jwt\shortcuts.py", line 16, in get_token
    return jwt_settings.JWT_ENCODE_HANDLER(payload, context)
  File "<path-to-project>\venv\lib\site-packages\graphql_jwt\utils.py", line 37, in jwt_encode
    return jwt.encode(
graphql.error.located_error.GraphQLLocatedError: 'str' object has no attribute 'decode'
```

after adding `ALLOW_LOGIN_NOT_VERIFIED` as **False**, the error is gone (no `GRAPHQL_AUTH` in the `settings.py` when the error is showing up). I just simply following the step and really not sure if I miss any step at all.

# Requirements

```
aniso8601==7.0.0
asgiref==3.3.1
Django==3.1.4
django-filter==2.4.0
django-graphql-auth==0.3.15
django-graphql-jwt==0.3.0
graphene==2.1.8
graphene-django==2.14.0
graphql-core==2.3.2
graphql-relay==2.0.1
promise==2.3
PyJWT==2.0.0
pytz==2020.4
Rx==1.6.1
singledispatch==3.4.0.3
six==1.15.0
sqlparse==0.4.1
text-unidecode==1.3
```

**Comment by ariomoklo** [comment]
Found the issue solution in [django-graphql-jwt issue #241](https://github.com/flavors/django-graphql-jwt/issues/241). Issue come from pyjwt. Solved by pinning the version of pyjwt to <2.
